model_names: ["combined_mlp", "combined_cnn"]
weights: [True]
norm_types: ["std_full"]
lrs: [5e-4]
n_folds: 3
finetune: False
n_parallel_training: 0
fixed_params:
  data_dir: "data/mair_cs"
  run_dir: "experiments/mair_cs"
  batch_size: 32
  n_workers: 2
  in_dim: 1024
  hidden_dims: "none"
  use_amp: False