model_names: ["unet"]
weights: [True]
norm_types: ["std_full"]
lrs: [1e-3, 5e-3, 1e-2]
n_folds: 3
finetune: False
fixed_params:
  data_dir: "data/mair_cs"
  run_dir: "experiments/mair_cs"
  batch_size: 16
  n_workers: 2
  in_dim: 1024
  hidden_dims: "20,20"
  use_amp: False