model_names: ["scan"]
weights: [True]
norm_types: ["none"]
lrs: [1e-3]
n_folds: 3
finetune: False
n_parallel_training: 0
fixed_params:
  data_dir: "data/msat_cs"
  run_dir: "experiments/msat_cs"
  batch_size: 16
  n_workers: 2
  in_dim: 1080
  hidden_dims: "20,20"
  use_amp: True