model_names: ["mlp"]
weights: [True]
norm_types: ["none"]
lrs: [1e-4, 5e-4, 1e-3, 1e-2]
n_folds: 3
finetune: False
n_parallel_training: 0
fixed_params:
  data_dir: "data/msat_cs"
  run_dir: "experiments/msat_cs"
  batch_size: 16
  n_workers: 0
  in_dim: 1080
  hidden_dims: "20,20"
  use_amp: True